# Generated by Django 5.0.3 on 2024-06-24 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='guestbook',
            name='write_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
